#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Last update on Thu Sep 24 09:22:26 2020

@author: GS
"""

import pandas as pd

data = pd.read_whatever("dataframe")



'''Data exploration'''
data.describe()                         #Variable v1 has values < 0
data.loc[data['v1'] < 0]                #Delete them



'''Opt 1: Delete the column'''
data.drop('v1', 1, inplace=True)

'''Opt 2: Delete the wrong observations'''
data.drop(data[data['v1'] < 0].index, inplace=True)
                            
'''Opt 3: Impute the wrong values with the mean'''                                                                     
data['v1'].mean()
# !=
data['v1'][data.age > 0].mean()
data.loc[data.v1 < 0, 'v1'] = data['v1'][data.v1 > 0].mean()
